name: 'Build LaTex Document with Biber'
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - uses: actions/cache@v2
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: "latest"
      - name: Run Tectonic + Biber
        run: |
          mkdir -p results
          git diff --name-only --diff-filter AMR HEAD~1 | grep ".*\.tex" | while read line
          do
            tectonic -X compile "$line" -Z shell-escape --outdir ./results
          done
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: pdf-results
          path: results/*.pdf
      - name: Push results to the repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*.pdf results/*.pdf" 
          commit_options: "--no-verify --signoff"
          commit_message: "chore: Update PDF documents"
